[workspace]
resolver = "3"
members = ["criware-utf", "criware-utf-core", "criware-utf-macros"]

[workspace.package]
description = "Implementation of the UTF table format used in CRIWARE CPK files"
version = "0.2.0"
license = "GPL-3.0-or-later"