[package]
name = "criware-utf-core"
description = "Core components for parsing/writing UTF tables in CRIWARE CPK files"
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
thiserror = "2.0.14"
