[package]
name = "criware-utf"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-or-later"
license-file = "LICENSE"

[dependencies]
criware-utf-core = { version = "0.1.0", path = "../criware-utf-core" }
criware-utf-derive = { version = "0.1.0", path = "../criware-utf-derive" }
